ksr/api/urls.py
from rest_framework import routers
import viewsets

router = routers.DefaultRouter()
router.register('jobs', viewsets.RouterJobViewSet)
urlpatterns = router.urls

ksr/jobs/urls.py
from django.conf.urls import url
import views

app_name = 'jobs'
urlpatterns = [
    url(r'^$', views.RouterJobList.as_view(), name='list'),
    url(r'^(?P<pk>[0-9]+)/$', views.RouterJobDetail.as_view(), name='detail'),
]

ksr/urls.py
from django.conf.urls import url, include
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^api/', include('ksr.api.urls')),
    url(r'^jobs/', include('ksr.jobs.urls')),
    url(r'^$', lambda r: HttpResponseRedirect('jobs/')),
]

ksr/jobs/models.py
from datetime import datetime
import json
import logging
import os
import subprocess
import signal
import sys

from django.conf import settings
from django.db import models
from django.dispatch import receiver
import requests

log = logging.getLogger(__name__)


class RouterJob(models.Model):

    # The Kaizen job instance ID
    jid = models.BigIntegerField()

    # The name given to the job
    name = models.CharField(max_length=256)

    # JSON field containing the definition
    definition = models.TextField()

    # Callback URL
    callback_url = models.CharField(max_length=256)

    # Current exit status of the process
    exit_code = models.IntegerField(blank=True, null=True)

    # Pid of the process
    pid = models.IntegerField(blank=True, null=True)

    # Start and End times of the process
    start_time = models.DateTimeField(null=True)
    end_time = models.DateTimeField(null=True)

    # Notification Timestamps
    running_notified = models.DateTimeField(null=True)
    exit_notified = models.DateTimeField(null=True)

    @property
    def json_definition(self):
        return json.loads(self.definition)

    @property
    def is_running(self):
        return self.pid is not None and self.exit_code is None

    @property
    def is_finished(self):
        return self.pid is not None and self.exit_code is not None

    @property
    def is_launching(self):
        return self.pid is None

    @property
    def is_succeeded(self):
        return self.is_finished and self.exit_code == 0

    @property
    def is_failed(self):
        return self.is_finished and not self.is_succeeded

    def kill(self, kill_signal=signal.SIGKILL):
        if not self.is_finished:
            # Kill the entire process group since we changed it when
            # fork/exec'ing
            os.killpg(self.pid, kill_signal)

    class Meta:
        ordering = ['-exit_notified', '-running_notified']


class RouterJobMsg(models.Model):

    # The job this message relates to
    job = models.ForeignKey(RouterJob)

    # The url the message is to be sent to
    url = models.TextField()

    # The JSON message contents
    msg = models.TextField()

    # When the message was created
    created_at = models.DateTimeField(auto_now_add=True)

    # When the message was successfully sent
    sent_at = models.DateTimeField(blank=True, null=True)

    def send(self):
        """ Send this message """
        try:
            requests.post(
                self.url, data=self.msg, headers={'Content-Type': 'application/json'},
                auth=requests.auth.HTTPBasicAuth(settings.KAIZEN_USERNAME, settings.KAIZEN_PASSWORD)
            ).raise_for_status()
        except requests.HTTPError:
            log.exception("Failed to send router job message: %s", self)
            raise
        self.sent_at = datetime.utcnow()
        self.save()


@receiver(models.signals.post_save, sender=RouterJob)
def on_router_job_created(sender, instance=None, created=False, **kwargs):
    """ Launch a ksr-worker process to manage the job from now on.
    The worker survives for the duration of the job. However we want to
    respond to the API request now. So we spawn the worker process and detach
    it from ourselves by changing the session and group IDs. """
    if created:

        def detach():
            os.setsid()
            os.setpgrp()

        subprocess.Popen(
            [settings.KSR_WORKER, str(instance.id)],
            stdin=open(os.devnull, 'r'),
            stdout=sys.stdout,
            stderr=sys.stderr,
            preexec_fn=detach,
            close_fds=True,
            env=os.environ
        )

ksr/jobs/views.py
from django.views import generic
from ksr.jobs.models import RouterJob


class RouterJobList(generic.ListView):
    model = RouterJob
    paginate_by = 20


class RouterJobDetail(generic.DetailView):
    model = RouterJob

ksr/jobs/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load activeurl %}
<html>
  <head>
    <title>KSR {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'semantic/semantic.min.css' %}">
  </head>
  <body>
    {% activeurl parent_tag="a" %}
    <nav class="ui top menu">
      <div class="header item">Kaizen SSH Router</div>
      <a class="item" href="{% url 'jobs:list' %}">Jobs</a>
    </nav>
    {% endactiveurl %}

    <main class="ui page container">
    {% block content %}
    {% endblock %}
    </main>

    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'semantic/semantic.min.js' %}"></script>
    <script>
$(".ui.dropdown").dropdown();
$(".ui.form").form();
$('.tabular.menu .item').tab();
$('.ui.accordion').accordion();
    </script>
  </body>
</html>

ksr/jobs/templates/jobs/routerjob_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} - {{ routerjob.jid }}{% endblock %}

{% block content %}
<h1>KSR Router Job {{ routerjob.jid }}</h1>

Some details...
{% endblock %}

ksr/jobs/templates/jobs/routerjob_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} - Jobs{% endblock %}

{% block content %}

<h1>KSR Router Jobs</h1>

<div class="ui relaxed divided list">
  {% for job in routerjob_list %}
  <div class="item">
    {% if job.is_launching %}
    <i title="launching" class="large radio middle aligned icon"></i>
    <div class="content">
      <a class="header" href="{% url 'jobs:detail' job.id %}">{{ job.name }}</a>
      <div class="description">Waiting for launch...</div>
    </div>
    {% elif job.is_running %}
    <i title="running" class="large selected radio middle aligned icon"></i>
    <div class="content">
      <a class="header" href="{% url 'jobs:detail' job.id %}">{{ job.name }}</a>
      <div class="description">Started {{ job.start_time | naturaltime }} with pid {{ job.pid }}</div>
    </div>
    {% elif job.is_succeeded %}
    <i title="succeeded" class="large check circle outline middle aligned icon"></i>
    <div class="content">
      <a class="header" href="{% url 'jobs:detail' job.id %}">{{ job.name }}</a>
      <div class="description">Finished successfully {{ job.start_time | naturaltime }}</div>
    </div>
    {% elif job.is_failed %}
    <i title="failed" class="large remove circle outline middle aligned icon"></i>
    <div class="content">
      <a class="header" href="{% url 'jobs:detail' job.id %}">{{ job.name }}</a>
      <div class="description">Finished {{ job.start_time | naturaltime }} with exit code {{ job.exit_code }}</div>
    </div>
    {% endif %}
  </div>
  {% endfor %}
</div>

{% if is_paginated %}
<div class="ui pagination menu">

  {# FIXME: lots of pages? #}

  {% for linkpage in paginator.page_range %}
  <a class="item{% ifequal linkpage page_obj.number %} active{% endifequal %}" href="?page={{ linkpage }}">{{ linkpage }}</a>
  {% endfor %}

</div>
{% endif %}

{% endblock content %}